client_config_backend: settings
client_config:
  client_id: 605723797942-1v7c7jic9r60epqoaagjum3lg1pnufui.apps.googleusercontent.com
  client_secret: ZszmVBXlXiwJTo50awVuwBsK

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
